spring:
  boot:
    admin:
      client:
        url: http://localhost:8084
  application:
    name: spring-cloud-zipkin

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# 2.10版本及其以后版本需要配置
management:
  metrics:
    web:
      server:
        auto-time-requests: false